channels: 
  - conda-forge
dependencies:
  # Required
  - python==3.11.5
  - shapely
  - pandas
  - geopandas>=0.9.*
  - pip
  # Use pip to install rhp from dev branch of git repo
    - git+https://github.com/manaakiwhenua/rhealpixdggs-py.git@demaion/raster2dggs
